export const TAG_LABELS: Record<string, string> = {
  array: "数组",
  hash: "哈希表",
  string: "字符串",
  "string-matching": "字符串匹配",
  kmp: "KMP",
  "z-algorithm": "Z函数",
  "rolling-hash": "滚动哈希",
  manacher: "马拉车",
  trie: "字典树",
  "ac-automaton": "AC自动机",
  "suffix-array": "后缀数组",
  stack: "栈",
  queue: "队列",
  deque: "双端队列",
  heap: "堆",
  "two-pointers": "双指针",
  "sliding-window": "滑动窗口",
  "binary-search": "二分",
  "binary-search-answer": "二分答案",
  "prefix-sum": "前缀和",
  "2d-prefix": "二维前缀和",
  "difference-array": "差分数组",
  contribution: "贡献法",
  discretization: "离散化",
  "monotonic-stack": "单调栈",
  "monotonic-queue": "单调队列",
  greedy: "贪心",
  "regret-greedy": "反悔贪心",
  dp: "动态规划",
  knapsack: "背包",
  "digit-dp": "数位DP",
  "interval-dp": "区间DP",
  "partition-dp": "划分DP",
  "state-machine": "状态机DP",
  "tree-dp": "树形DP",
  rerooting: "换根DP",
  bitmask: "状压",
  "matrix-expo": "矩阵快速幂",
  backtracking: "回溯",
  "divide-and-conquer": "分治",
  memoization: "记忆化搜索",
  enumeration: "枚举",
  math: "数学",
  newton: "牛顿迭代",
  "ternary-search": "三分",
  "binary-exponentiation": "快速幂",
  "number-theory": "数论",
  combinatorics: "组合",
  "bit-manipulation": "位运算",
  "inclusion-exclusion": "容斥",
  sorting: "排序",
  quickselect: "快速选择",
  simulation: "模拟",
  interval: "区间",
  constructive: "构造",
  matrix: "矩阵",
  grid: "网格",
  graph: "图",
  bfs: "广度优先",
  dfs: "深度优先",
  "flood-fill": "泛洪",
  "shortest-path": "最短路",
  dijkstra: "Dijkstra",
  "0-1-bfs": "0-1 BFS",
  floyd: "Floyd",
  "topological-sort": "拓扑排序",
  "union-find": "并查集",
  mst: "最小生成树",
  scc: "强连通分量",
  "max-flow": "最大流",
  "bipartite-matching": "二分图匹配",
  eulerian: "欧拉路",
  "functional-graph": "基环树",
  "binary-lifting": "倍增",
  lca: "最近公共祖先",
  diameter: "树的直径",
  "two-sat": "2-SAT",
  "sweep-line": "扫描线",
  offline: "离线",
  "segment-tree": "线段树",
  fenwick: "树状数组",
  "sparse-table": "ST表",
  "sqrt-decomposition": "根号分治",
  "meet-in-the-middle": "折半搜索",
  geometry: "几何",
  gaussian: "高斯消元",
  probability: "概率",
  fft: "FFT",
  game: "博弈",
  randomized: "随机",
  "linked-list": "链表",
  tree: "树",
  weekly: "本周新题",
};

export const WEEKLY_TAG = "weekly";

export function tagLabel(id: string): string {
  return TAG_LABELS[id] || id;
}

export const TAG_FAMILIES: { id: string; label: string; tags: string[] }[] = [
  { id: "sliding-window", label: "滑窗 / 双指针", tags: ["sliding-window", "two-pointers"] },
  { id: "binary-search", label: "二分", tags: ["binary-search", "binary-search-answer", "ternary-search"] },
  { id: "monotonic", label: "单调栈队列", tags: ["monotonic-stack", "monotonic-queue", "contribution"] },
  { id: "grid", label: "网格图", tags: ["grid", "matrix", "bfs", "dfs", "flood-fill"] },
  { id: "bits", label: "位运算", tags: ["bit-manipulation", "bitmask"] },
  {
    id: "graph",
    label: "图论",
    tags: [
      "graph",
      "shortest-path",
      "dijkstra",
      "0-1-bfs",
      "floyd",
      "topological-sort",
      "union-find",
      "mst",
      "scc",
      "max-flow",
      "bipartite-matching",
      "eulerian",
      "functional-graph",
      "two-sat",
    ],
  },
  {
    id: "dp",
    label: "DP",
    tags: [
      "dp",
      "memoization",
      "knapsack",
      "state-machine",
      "partition-dp",
      "interval-dp",
      "digit-dp",
      "tree-dp",
      "rerooting",
      "matrix-expo",
      "game",
      "probability",
    ],
  },
  {
    id: "ds",
    label: "数据结构",
    tags: [
      "prefix-sum",
      "2d-prefix",
      "difference-array",
      "stack",
      "queue",
      "deque",
      "heap",
      "trie",
      "fenwick",
      "segment-tree",
      "sparse-table",
      "hash",
      "discretization",
    ],
  },
  {
    id: "math",
    label: "数学 / 数值",
    tags: [
      "math",
      "number-theory",
      "combinatorics",
      "inclusion-exclusion",
      "geometry",
      "gaussian",
      "newton",
      "binary-exponentiation",
      "fft",
      "randomized",
    ],
  },
  {
    id: "greedy",
    label: "贪心 / 构造",
    tags: ["greedy", "regret-greedy", "interval", "constructive", "enumeration", "simulation"],
  },
  {
    id: "tree",
    label: "树与分治",
    tags: [
      "backtracking",
      "binary-lifting",
      "lca",
      "diameter",
      "tree-dp",
      "rerooting",
      "divide-and-conquer",
      "meet-in-the-middle",
    ],
  },
  {
    id: "string",
    label: "字符串",
    tags: [
      "string",
      "string-matching",
      "kmp",
      "z-algorithm",
      "manacher",
      "rolling-hash",
      "ac-automaton",
      "suffix-array",
      "trie",
    ],
  },
];
